#!/bin/sh

echo "Waiting ${INITIAL_DELAY:=60} seconds..."
sleep "${INITIAL_DELAY}"

while true; do
  /usr/bin/curator --config /etc/curator/config.yml /etc/curator/actions.yml

  echo "Sleeping ${PERIOD:=86400} until next run..."
  sleep "${PERIOD}"
done
